### ISSUE TITLE
Update colour tokens before the 2.0 beta

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#3067]
During the workshop we discovered some inconsistencies in the token naming, so we’ll have to make some changes. One thing I tried that didn’t work, was to omit the “default” segment. That means that as CSS variables we would have:

```css
:root {
  --eds-color-text-notification-info: var(...);
  --eds-color-text-notification-info-on-inverted: var(...);
  ...
}
``` 

One advantage of this approach is that we keep the token names as short as possible, but a disadvantage is that in Figma that means the tokens will be sorted under different headers. 

![image](https://github.com/equinor/design-system/assets/2081882/29358ae0-260d-4485-8023-1b5531310bfb)

While if we keep segments such as “default” it’s easier to see just by glancing at the tokens which ones are grouped together:

![image](https://github.com/equinor/design-system/assets/2081882/4f068165-473b-4674-b622-e4be1ce0ae95)

However, there are certain cases where the word “default” should be replaced with “enabled” and “resting”, the difference being that where we have `hover` and `pressed` states, the default state should be “enabled” and in cases where we have an `active` state, the default should be `resting` – since that’s the opposite of `active`.

I’ve started going through the variables in a branch in Figma called [“post EDC cleanup”](https://www.figma.com/file/yfAgV2Mv60LiGFVPS98Z45/branch/Z3OC9bp1mCFBw9eH7KbhDb/%F0%9F%8E%A8-EDS-Tokens?type=design&node-id=150-95044&mode=design&t=TXrOgu1JgiYwIL8o-11).

In addition to that there are colour tokens that aren’t finished yet, and @benteljones and I have also discussed whether we should break more tokens into groups. One of the areas where we need more clarity is for example the `text interactive` tokens, where it’s not immediately clear where and how to use them:

```css
:root {
  --eds-color-text-interactive-enabled: var(...);
  --eds-color-text-interactive-hover: var(...);
  --eds-color-text-interactive-pressed: var(...);
  --eds-color-text-interactive-resting: var(...);
  --eds-color-text-interactive-active: var(...);
  --eds-color-text-interactive-disabled: var(...);
}
```

There’s also some work remaining with the chips, banner and card colours in dark mode. These are cases where we have the same colour in light mode, but since dark mode is more rich and complex, we need different colours.
