### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by vnys** [equinor/design-system#343]
- [x] Update all dependencies
- [x] Add optional chaining to Eslint config
  - Add `babel-eslint` as dev dependency in the root

```yaml
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
```
